name: appsupreagro
description: Supre agro pedidos.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.2

  cupertino_icons: ^1.0.2
  http: ^0.13.6
  modal_bottom_sheet: ^3.0.0-pre
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.2
  logger: ^2.0.2
  dio: ^5.3.2
  flutter_native_splash: ^2.2.19
  uuid: ^4.1.0
  brasil_fields: ^1.12.0
  intl: ^0.18.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/launcher.png
